- name: Pull and Run docker image
  hosts: host_machine
  tasks:
#    - name: Pull abhigna4443/calculator_project
#      docker_image:
#        name: abhigna4443/calculator_project
#        source: pull
#        

    - name: pull image
      shell: docker pull abhigna4443/calculator_project:latest

    - name: run container
      shell: docker run -i -t --name calculator -d bhigna4443/calculator_project
