- name: Pull and Run docker image
  hosts: host_machine
  tasks:

    - name: Remove old containers
      shell: docker ps -aq --filter name="calculator" | xargs docker stop | xargs docker rm

    - name: Pull Image
      shell: docker pull abhigna4443/calculator_project:latest

    - name: Run the container
      shell: docker run -i -t --name calculator_project -d abhigna4443/calculator_project
